// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqbvaylwoxizcajdsmcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxYnZheWx3b3hpemNhamRzbWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzE2NTEsImV4cCI6MjA3MTAwNzY1MX0.GK7WxJv4zMmeJNpjXR5I81gOto7T6GpX0x7q89Y99UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});